Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [9]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()

features = iris.data

mean=np.mean(features,axis=0)
median=np.median(features,axis=0)
standard=np.std(features,axis=0)
variance = np.var(features,axis=0)

for i, name in enumerate(iris.feature_names):
    print(f"--- {name} ---")
    print(f"Mean: {mean[i]} | Median: {median[i]}")
    print(f"Std Dev: {standard[i]} | Variance: {variance[i]}\n")

#If one feature has a range of 1–7 (high variance) and another is 0.1–0.5 (low variance),
#the model will think the high-variance feature is "more important" simply because the numbers are bigger.

sepal_length= iris.data[:,0].reshape(-1,1)
sepal_width= iris.data[:,1].reshape(-1,1)
petal_length= iris.data[:,2].reshape(-1,1)
petal_width= iris.data[:,3].reshape(-1,1)


print(sepal_length)
print(sepal_width)
print(petal_length)
print(petal_width)

#Models expect this format for uniformity and matric multiplication 

--- sepal length (cm) ---
Mean: 5.843333333333335 | Median: 5.8
Std Dev: 0.8253012917851409 | Variance: 0.6811222222222222

--- sepal width (cm) ---
Mean: 3.057333333333334 | Median: 3.0
Std Dev: 0.43441096773549437 | Variance: 0.1887128888888887

--- petal length (cm) ---
Mean: 3.7580000000000027 | Median: 4.35
Std Dev: 1.7594040657753032 | Variance: 3.0955026666666674

--- petal width (cm) ---
Mean: 1.199333333333334 | Median: 1.3
Std Dev: 0.7596926279021594 | Variance: 0.5771328888888888

[[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]
 [5.4]
 [5.1]
 [4.6]
 [5.1]
 [4.8]
 [5. ]
 [5. ]
 [5.2]
 [5.2]
 [4.7]
 [4.8]
 [5.4]
 [5.2]
 [5.5]
 [4.9]
 [5. ]
 [5.5]
 [4.9]
 [4.4]
 [5.1]
 [5. ]
 [4.5]
 [4.4]
 [5. ]
 [5.1]
 [4.8]
 [5.1]
 [4.6]
 [5.3]
 [5. ]
 [7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]
 [5.7]
 [6.3]
 [4.9]
 [6.6]
 [5.2]
 [5. ]
 [5.9]
 [6. ]
 [6.1]
 [5.6]
 [6.7]
 [5.6]
 [5.8]
 [6.2]
 [5.6]
 [5.9]
 [6.1]

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [ ]:
dataset = features[:100,-2:]
masked_data = dataset[dataset[:,0]>dataset.mean()]
print(f"Mean: {dataset.mean()}")
print(masked_data)


#You can filter out data that are just noise and not provide any valuable information ot do not give any valuable prection value


Mean: 1.8235000000000001
[[1.9 0.2]
 [1.9 0.4]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]
 [4.6 1.4]
 [4.  1.2]
 [3.3 1. ]
 [4.2 1.3]
 [4.2 1.2]
 [4.2 1.3]
 [4.3 1.3]
 [3.  1.1]
 [4.1 1.3]]


Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [1]:
from sklearn.datasets import load_iris
import numpy as np

iris= load_iris()
dataset= iris.data

mean = np.mean(dataset,axis=0)
std = np.std(dataset,axis=0)

standardization = (dataset-mean)/std
print("Mean",np.abs(np.mean(standardization,axis=0).round(6)))
print("Std", np.std(standardization,axis=0))

Mean [0. 0. 0. 0.]
Std [1. 1. 1. 1.]


In [46]:
import seaborn as sns
df = sns.load_dataset("titanic")

print(f"HEAD\n {df.head()}")
print(f"Tail\n {df.tail()}")
print(f"Info\n {df.info()}")
print(f"Descrive\n {df.describe()}")

#Idefntifying features is importand so that we do not get noise from our data. Misusing thw data will result to 
#worng outcome. ex Treading zip cod as a meaningful number model will give it more vaule as a high number however it should not

HEAD
    survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
Tail
      survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [2]:
import seaborn as sns

df = sns.load_dataset("titanic")

female = df[(df['sex']=="female") & (df['pclass']==1)]
female_survival_rate = female['survived'].mean()
overall_survival_rate = df['survived'].mean()
print(female_survival_rate)
print(overall_survival_rate)
print("Compare", female_survival_rate - overall_survival_rate)

#For us to create more accurate features how many wfemale did survive in other pclasses
#From there we could see what better survival rate does the 1st class has
#If the rate is similar then we can compare other feautures like sex and see from there we can see what feature has a major factor on survival rate

0.9680851063829787
0.3838383838383838
Compare 0.5842467225445949


Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())
df['embarked']= df['embarked'].fillna(df['embarked'].mode()[0])
print(df['age'].isna().sum())
print(df['embarked'].isna().sum())

#Due to the fact that not all feautures are numerical we need different strategies for them 

0
0


Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [3]:
df['familysize'] = df['sibsp'] + df['parch'] + 1

print(df['familysize'])

is_alone = df['familysize'] == 1

print(f"{df[is_alone]['survived'].mean():.2%}")

#Engineered features give us more valuable data than raw data.
#By creating features we can get valuable insigth for predictions 

0      2
1      2
2      1
3      2
4      1
      ..
886    1
887    1
888    4
889    1
890    1
Name: familysize, Length: 891, dtype: int64
30.35%


Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [4]:
df = sns.load_dataset("tips")

print(df.head())

average_tip = df.groupby('day',observed=False)['tip'].mean()
print(average_tip)

average_total_bill_gender = df.groupby('sex',observed=False)['total_bill'].mean()
print(average_total_bill_gender)

print('Max', average_tip.idxmax(), average_tip.max())

#These features help us understand better what days and gender spends the most so we can arrange accordingly

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64
sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64
Max Sun 3.2551315789473683


Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [5]:
df = sns.load_dataset("tips")

print(df.head())

total_bill_higher_20_tip_lower_3 = df[(df['total_bill']>20) & (df['tip']<3)]

print(total_bill_higher_20_tip_lower_3)

size_total = df.groupby('size', observed=False)[['total_bill','tip']].mean()
gender_total = df.groupby('sex', observed=False)[['total_bill', 'tip']].mean()
day_total = df.groupby(['day','time'], observed=False)[['total_bill', 'tip']].mean()

print(size_total)
print(gender_total)
print(day_total)

#Most of the data are normal the only under-tipping that we see is the bigger groups while the 1 froup gives around 1.5
#6 people give around 5.2 thats less than 1 
#also friday lunch total is an anomaly while all the other days are above 17 that one is less

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
     total_bill   tip     sex smoker   day    time  size
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
48        28.55  2.05    Male     No   Sun  Dinner     3
57        26.41  1.50  Female     No   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
113       23.95  2.55    Male     No   Sun  Dinner     2
119       24.08  2.92  Female     No  Thur   Lunch     4
129       22.82  2.18    Male     No  Thur   Lunch     3
131       20.27  2.83  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinne

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [6]:
import numpy as np

arr1=np.random.rand(3,2)
arr2=np.array([7,8,9,10,11,12])

print(arr1)
arr2_reshape = arr2.reshape(3,2)

print(arr2_reshape)

v = np.vstack([arr1, arr2_reshape])
h = np.hstack([arr1,arr2_reshape])

print(v)
print(h)

v_reshaped = v.reshape(2,6)
h_reshaped = h.reshape(2,6)

print(v_reshaped)
print(h_reshaped)

#Reshaping is crucial as mathematicla algorithms require these arrays to fit together perfectly.

[[0.23407563 0.15140487]
 [0.91483483 0.78899344]
 [0.04634419 0.70645868]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 0.23407563  0.15140487]
 [ 0.91483483  0.78899344]
 [ 0.04634419  0.70645868]
 [ 7.          8.        ]
 [ 9.         10.        ]
 [11.         12.        ]]
[[ 0.23407563  0.15140487  7.          8.        ]
 [ 0.91483483  0.78899344  9.         10.        ]
 [ 0.04634419  0.70645868 11.         12.        ]]
[[ 0.23407563  0.15140487  0.91483483  0.78899344  0.04634419  0.70645868]
 [ 7.          8.          9.         10.         11.         12.        ]]
[[ 0.23407563  0.15140487  7.          8.          0.91483483  0.78899344]
 [ 9.         10.          0.04634419  0.70645868 11.         12.        ]]


Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [3]:
import pandas as pd
df = sns.load_dataset('titanic')
print(df.head())
df.isnull().sum()

df['age'] = df['age'].fillna(df['age'].median())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
df.drop(columns='deck',inplace=True)

df['age'] = df['age'] / df['age'].max()
df['fare'] = df['fare'] / df['fare'].max()
print("Normalize age", df['age'])

data = pd.get_dummies(df, columns=['sex', 'embarked'], drop_first=True)
df.isnull().sum()

tips_array = df.to_numpy()
print(tips_array)

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
Normalize age 0      0.2750
1      0.4750
2      0.3250
3      0.4375
4      0.4375
        ...  
886    0.3375
887    0.2375
888    0.3500
889    0.3250
890    0.4000
Name: age, Length: 891, dtype: float64
[[0 3 'male'

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [4]:
from sklearn.datasets import load_iris
import numpy as np

iris= load_iris()
dataset= iris.data

corr_matric = np.corrcoef(dataset,rowvar=False)

print(corr_matric)
#Higly correlated features 1-3 1-4 3-4 
#We drop column 4 as it is identical with 3 and will create unesecary weight on the model

data_new = np.delete(dataset,3,axis=1)

corr_matric = np.corrcoef(data_new,rowvar=False)

print(corr_matric)

#overfitting is when the model is so complex that it memoroizes noise
#it is better to have lower accuracy with less features that a bit higher accuracy with a lot more features

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
[[ 1.         -0.11756978  0.87175378]
 [-0.11756978  1.         -0.4284401 ]
 [ 0.87175378 -0.4284401   1.        ]]


Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [5]:
import seaborn as sns

df = sns.load_dataset('titanic')

def age_group(age):
    if age > 50 :
        return 'Senior'
    elif age > 18:
        return 'Adult'
    else:
        return 'Child'
        
df['age_group']= df['age'].apply(age_group)  
print(df)

print(f"Survival by age group: {df.groupby('age_group')['survived'].mean().map('{:.2%}'.format)}")
print(f"Survival by age group: {df.groupby(['age_group','sex'])['survived'].mean().map('{:.2%}'.format)}")

#Adults has the highest survival rate

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [6]:
import numpy as np

np.random.seed(42)
errors = np.random.normal(0,1,1000)

mean= np.mean(errors)
std = np.std(errors)

outliers = errors[(errors< (mean - 2 * std)) | ( errors > (mean + 2 *std))]

print(outliers)

#High variance is when a o model with simila dataset produce complute different results
#this is due to complex modeling,, this create incostencies.

[-1.95967012 -2.6197451  -1.98756891  2.46324211  2.19045563  2.72016917
  3.85273149  2.31465857  2.14394409 -2.02514259  2.1221562  -3.24126734
  2.13303337 -1.9520878   2.09238728  2.15318246  2.18980293 -2.12389572
  2.06074792 -2.03923218 -2.0674421  -2.30192116  3.07888081 -2.4716445
  2.0754008  -2.03812454 -2.21113531  2.27069286  2.44575198 -2.69688664
  2.5733598  -2.65096981 -2.07339023 -2.08192941  2.63238206  2.56008454
  2.29889812  2.45530014  2.01020454  2.52693243  2.16325472 -2.19880596
 -2.42387933 -2.04173487]


Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [7]:
df = sns.load_dataset("tips")

print(df)

df['tip_percentage'] = (df['tip'] / df['total_bill']).fillna(0) * 100

tip_percentage_group =df.groupby(['day','time'], observed=False)['tip_percentage'].mean()
print(tip_percentage_group)
print(tip_percentage_group.idxmax(),tip_percentage_group.max())


#Fri night is the highest paying tip so providing there your best service could be a good idea

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
day   time  
Thur  Lunch     16.130074
      Dinner    15.974441
Fri   Lunch     18.876489
      Dinner    15.891611
Sat   Lunch           NaN
      Dinner    15.315172
Sun   Lunch           NaN
      Dinner    16.689729
Name: tip_percentage, dtype: float64
('Fri', 'Lunch') 18.87648882948433